#@TYPE: Machine
#@NAME: NXP i.MX 93 Lite EVB Platform
#@SOC: i.MX93
#@DESCRIPTION: Machine configuration for NXP i.MX 93 11x11 FRDM with LPDDR4X
#@MAINTAINER: Wig Cheng <dev@ieiworld.com>

MACHINEOVERRIDES =. "imx93-11x11-lpddr4x-evk:"
require conf/machine/imx93-11x11-lpddr4x-evk.conf

KERNEL_DEVICETREE:append:use-nxp-bsp = " \
    freescale/imx93-lite93-evb.dtb \
    freescale/imx93-lite93-evb-imx219.dtbo \
    freescale/imx93-lite93-evb-ov5640.dtbo \
    freescale/imx93-lite93-evb-rpi-panel-v2.dtbo \
 "

UBOOT_CONFIG_BASENAME = "imx93_11x11_frdm"

DDR_FIRMWARE_NAME = " \
    lpddr4_dmem_1d_v202201.bin \
    lpddr4_dmem_2d_v202201.bin \
    lpddr4_imem_1d_v202201.bin \
    lpddr4_imem_2d_v202201.bin \
"
